spring:
  codec:
    max-in-memory-size: 20MB

logging:
  level:
    root: WARN
    be.vlaanderen.informatievlaanderen.ldes.ldio.Application: INFO
    be.vlaanderen.informatievlaanderen.ldes: WARN

management:
  tracing:
    enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always