spring:
  codec:
    max-in-memory-size: 20MB

logging:
  level:
    root: WARN
    be.vlaanderen.informatievlaanderen.ldes.ldio.Application: INFO
    be.vlaanderen.informatievlaanderen.ldes: WARN

springdoc:
  swagger-ui:
    path: /v1/swagger
    urlsPrimaryName: base
