upstream backend {
    server ldes-server-backend:8080;
}

# server {
#     listen 8080;
    
#     include /etc/nginx/mime.types;

#     location / {
#         proxy_pass http://ldes-server/;
#     }
# }

server {
    listen 8080;

    # gzip on;
    # gzip_types application/n-triples application/ld+json text/turtle application/n-quads application/rdf+protobuf;

    # location /admin {
    #     deny all;
    # }

    location / {
        proxy_pass http://backend/;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        # gzip_static on;
    }
}
