mongock:
  migration-scan-package: VSDS
springdoc:
  swagger-ui:
    path: /v1/swagger
management:
  tracing:
    enabled: false
  endpoints:
      web:
        exposure:
          include: prometheus,health
ldes-server:
  host-name: http://localhost:8080
spring:
  data:
    mongodb:
      database: bustang
      host: ldes-mongodb
      port: 27017
      auto-index-creation: true # This index is SUPER important, fragmentation takes multiple times longer without.

logging:
  level:
    be.vlaanderen.informatievlaanderen.ldes.server.ingest: DEBUG