global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ldes-server'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ldes-server:8080']
  - job_name: 'ldio-workbench'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['load-testing-ldio-workbench-workbench:8080']
